env_name: ant-medium-expert-v2
action_dim: 8
horizon_steps: 4
act_steps: 4
obs_dim: 111
cond_steps: 1
_target_: agent.eval.eval_reflow_agent_score.EvalScoreAgent
name: ant-medium-expert-v2_eval_score_mlp_ta4_td4
logdir: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/log/gym/eval/ant-medium-expert-v2_eval_score_mlp_ta4_td4/2026-01-26_13-01-54_42
base_policy_path: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/log/gym/finetune/ant-medium-expert-v2_ppo_reflow_mlp_score_ta4_td4/2026-01-19_02-54-31_seed3407/checkpoint/best.pt
normalization_path: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/data/gym/ant-medium-expert-v2/normalization.npz
seed: 42
device: cuda:0
sim_device: cuda:0
denoising_steps: 4
denoising_step_list:
- 4
load_ema: false
epsilon_t: 0.0
epsilon_schedule: constant
gamma_score: 1.0
eval_mode: true
batch_size: 128
n_steps: 500
render_num: 5
env:
  n_envs: 5
  name: ant-medium-expert-v2
  max_episode_steps: 1000
  reset_at_iteration: false
  save_video: true
  best_reward_threshold_for_success: 3
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/data/gym/ant-medium-expert-v2/normalization.npz
    multi_step:
      n_obs_steps: 1
      n_action_steps: 4
      max_episode_steps: 1000
      reset_within_step: true
model:
  _target_: model.flow.ft_ppo.ppoflow_score.PPOFlow
  device: cuda:0
  policy:
    _target_: model.flow.mlp_flow_score.FlowMLP
    horizon_steps: 4
    action_dim: 8
    cond_dim: 111
    time_dim: 16
    mlp_dims:
    - 512
    - 512
    - 512
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
  critic:
    _target_: model.common.critic.CriticObs
    cond_dim: 111
    mlp_dims:
    - 256
    - 256
    - 256
    activation_type: Mish
    residual_style: true
  actor_policy_path: null
  load_weights_in_init: false
  use_ema: false
  act_dim: 8
  horizon_steps: 4
  act_min: -1
  act_max: 1
  obs_dim: 111
  cond_steps: 1
  inference_steps: 4
  randn_clip_value: 3
  epsilon_t: 0.0
  epsilon_schedule: constant
  gamma_score: 1.0
  logprob_min: -20.0
  logprob_max: 20.0
  clip_ploss_coef: 0.01
  clip_ploss_coef_base: 0.01
  clip_ploss_coef_rate: 3
  clip_vloss_coef: null
  denoised_clip_value: 1.0
  logprob_debug_sample: false
  logprob_debug_recalculate: false
render_onscreen: false
record_video: true
