_target_: agent.eval.eval_reflow_agent_score.EvalScoreAgent
name: kitchen-complete-v0_eval_score_mlp_ta4_td4
logdir: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/log/gym/eval/kitchen-complete-v0_eval_score_mlp_ta4_td4/2025-12-24_06-49-09_42
base_policy_path: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/log/gym/finetune/kitchen-complete-v0_ppo_reflow_mlp_score_ta4_td4/2025-12-24_03-56-00_seed42/checkpoint/best.pt
normalization_path: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/data/gym/kitchen-complete-v0/normalization.npz
seed: 42
device: cuda:0
sim_device: cuda:0
env_name: kitchen-complete-v0
obs_dim: 60
action_dim: 9
denoising_steps: 4
denoising_step_list:
- 4
cond_steps: 1
horizon_steps: 4
act_steps: 4
epsilon_t: 0.0
epsilon_schedule: constant
gamma_score: 1.0
load_ema: false
batch_size: 128
n_steps: 280
render_num: 0
env:
  n_envs: 40
  name: kitchen-complete-v0
  max_episode_steps: 280
  reset_at_iteration: false
  save_video: false
  best_reward_threshold_for_success: 4.0
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/data/gym/kitchen-complete-v0/normalization.npz
    multi_step:
      n_obs_steps: 1
      n_action_steps: 4
      max_episode_steps: 280
      reset_within_step: true
model:
  _target_: model.flow.ft_ppo.ppoflow_score.PPOFlow
  device: cuda:0
  use_ema: false
  load_weights_in_init: false
  policy:
    _target_: model.flow.mlp_flow_score.FlowMLP
    horizon_steps: 4
    action_dim: 9
    cond_dim: 60
    time_dim: 16
    mlp_dims:
    - 256
    - 256
    - 256
    cond_mlp_dims:
    - 128
    - 32
    activation_type: Mish
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
  critic:
    _target_: model.common.critic.CriticObs
    cond_dim: 60
    mlp_dims:
    - 256
    - 256
    - 256
    activation_type: Mish
    residual_style: true
  actor_policy_path: /inspire/hdd/project/inference-chip/lijinhao-240108540148/research_clk/ReinFlow/log/gym/finetune/kitchen-complete-v0_ppo_reflow_mlp_score_ta4_td4/2025-12-24_03-56-00_seed42/checkpoint/best.pt
  act_dim: 9
  horizon_steps: 4
  act_min: -1
  act_max: 1
  obs_dim: 60
  cond_steps: 1
  inference_steps: 4
  epsilon_t: 0.0
  epsilon_schedule: constant
  gamma_score: 1.0
  randn_clip_value: 3
  logprob_min: -1.0
  logprob_max: 1.0
  clip_ploss_coef: 0.01
  clip_ploss_coef_base: 0.01
  clip_ploss_coef_rate: 3
  clip_vloss_coef: null
  denoised_clip_value: 1.0
  logprob_debug_sample: false
  logprob_debug_recalculate: false
render_onscreen: false
